[build]
  command = "npm run build"
  publish = "dist"      # This is where your compiled files go
  functions = "dist/netlify/functions" # This tells Netlify: "Look here for the actual functions"

[functions]
  node_bundler = "esbuild"
